services:
  - type: web
    name: chosanta-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: SESSION_SECRET
        generateValue: true
